channels:
  - conda-forge
dependencies:
  - r-base=3.6
  - r-tidyverse
  - r-rjava
  - r-tabulizer
  - r-knitr
  - r-magrittr
  - r-stm
  - r-tidytext
  - r-overviewR
  - r-readtext
  - r-quanteda
  - r-wesanderson
