install.packages("rJava")
install.packages("~/Downloads/rtracklayer_1.53.1.tar.gz",repos=NULL, type="source")
install.packages("knitr")
install.packages("tidyverse")
install.packages("magrittr")
install.packages("stm")
install.packages("tidytext")
install.packages("overviewR")
install.packages("readtext")
install.packages("quanteda")
install.packages("wesanderson")
